### ISSUE TITLE
Entering a negative number will still generate positive numbers

### ISSUE THREAD

**Issue by rgson** [Awfyboy/githubTest#4]
For example, if I enter "-100" then the text states that numbers "between 0 and -100" will be generated. However, it actually generates positive numbers instead.

**Comment by Awfyboy** [comment]
Whoops, I forgot about negative numbers! Will fix this as soon as possible.

**Comment by Awfyboy** [comment]
Fixed the issue, along with other arithmetical issues such as 0 not being within range.
